/**
 * @fileoverview gRPC-Web generated client stub for api.v1alpha1
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v3.21.12
// source: v1alpha1.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as v1alpha1_pb from './v1alpha1_pb';
import * as google_protobuf_empty_pb from 'google-protobuf/google/protobuf/empty_pb';
import * as google_protobuf_wrappers_pb from 'google-protobuf/google/protobuf/wrappers_pb';


export class QRCodeClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'binary';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorversion = new grpcWeb.MethodDescriptor(
    '/api.v1alpha1.QRCode/version',
    grpcWeb.MethodType.UNARY,
    google_protobuf_empty_pb.Empty,
    google_protobuf_wrappers_pb.StringValue,
    (request: google_protobuf_empty_pb.Empty) => {
      return request.serializeBinary();
    },
    google_protobuf_wrappers_pb.StringValue.deserializeBinary
  );

  version(
    request: google_protobuf_empty_pb.Empty,
    metadata: grpcWeb.Metadata | null): Promise<google_protobuf_wrappers_pb.StringValue>;

  version(
    request: google_protobuf_empty_pb.Empty,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: google_protobuf_wrappers_pb.StringValue) => void): grpcWeb.ClientReadableStream<google_protobuf_wrappers_pb.StringValue>;

  version(
    request: google_protobuf_empty_pb.Empty,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: google_protobuf_wrappers_pb.StringValue) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/api.v1alpha1.QRCode/version',
        request,
        metadata || {},
        this.methodDescriptorversion,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/api.v1alpha1.QRCode/version',
    request,
    metadata || {},
    this.methodDescriptorversion);
  }

  methodDescriptorgenerate = new grpcWeb.MethodDescriptor(
    '/api.v1alpha1.QRCode/generate',
    grpcWeb.MethodType.UNARY,
    v1alpha1_pb.Request,
    v1alpha1_pb.Response,
    (request: v1alpha1_pb.Request) => {
      return request.serializeBinary();
    },
    v1alpha1_pb.Response.deserializeBinary
  );

  generate(
    request: v1alpha1_pb.Request,
    metadata: grpcWeb.Metadata | null): Promise<v1alpha1_pb.Response>;

  generate(
    request: v1alpha1_pb.Request,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: v1alpha1_pb.Response) => void): grpcWeb.ClientReadableStream<v1alpha1_pb.Response>;

  generate(
    request: v1alpha1_pb.Request,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: v1alpha1_pb.Response) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/api.v1alpha1.QRCode/generate',
        request,
        metadata || {},
        this.methodDescriptorgenerate,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/api.v1alpha1.QRCode/generate',
    request,
    metadata || {},
    this.methodDescriptorgenerate);
  }

}

